### ISSUE TITLE
Release for Ruby 3 changes

### ISSUE THREAD

**Issue by Daniel-ltw** [ruby-numo/numo-narray#189]
I noticed that the latest version on Rubygems is 0.9.1.9.
That is compiled before all the ruby 3 changes/commits. 

Could we get a later version to be up on Rubygems? 
Or am I forced to run with the master branch and do my own compilation?

**Comment by kojix2** [comment]
@masa16
Since the beginning of 2021, there has been a significant increase in the number of daily downloads of numo-narray. I think most of the changes since the last release are ecosystem and CI improvements. But, it is worth releasing a new version.
https://bestgems.org/gems/numo-narray
![image](https://user-images.githubusercontent.com/5798442/122835332-1b4cbb00-d32b-11eb-811a-cb90067e776f.png)

**Comment by kojix2** [comment]
@Daniel-ltw 
v0.2.9.0 released. If everything is ok, please close this issue.

**Comment by Daniel-ltw** [comment]
Saw the release on RubyGems. 

Will close issue.
