### ISSUE TITLE
Sparse matrix

### ISSUE THREAD

**Issue by himkt** [ruby-numo/numo-narray#25]
Hi, I tried to create a 300k \* 300k matrix to find that sparse matrix is not supported in NArray.

Is there a plan to implement ?

**Comment by masa16** [comment]
I have no plan to implement sparse matrix. Contributions are welcome.

**Comment by himkt** [comment]
I see.
Thanks for replying !

**Comment by ohai** [comment]
In python, the dense matrix code and  the sparse matrix code are completely separated (numpy and scipy.sparse). 

Since the sparse matrix codes and the dense matrix codes have probably no common implementation, I think that it would be better to put the sparse matrix code into a separated namespace.

**Comment by masa16** [comment]
Numo::GSL::SpMatrix was implemented.
http://ruby-numo.github.io/gsl/doc/Numo/GSL/SpMatrix.html

It is nice if there is an interface to cuSPARSE:
https://developer.nvidia.com/cusparse

**Comment by kojix2** [comment]
We have this project, but it is not active.
https://github.com/mrkn/numo-sparse
